apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
  namespace: brain-tasks
  labels:
    app: brain-tasks-app
spec:
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brain-tasks-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: brain-tasks.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brain-tasks-app-service
            port:
              number: 80
